# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      MONGO_URI: mongodb://localhost:27017/file-management
      JWT_SECRET: your_jwt_secret
      PORT: 5000

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for backend
        working-directory: ./file-backend
        run: npm install

      - name: Run backend tests
        working-directory: ./file-backend
        run: npm test

      - name: Install dependencies for frontend
        working-directory: ./file-frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./file-frontend
        run: npm test